### PR TITLE
Add april community call

### PR DESCRIPTION
**Pull request by samumantha**

### CODE REVIEW

**Comment by bast** [comment]
Thanks! One worry from past experience: will half the people be in one hackmd and the other half in the other? Or should we remove the community call dates from the team meeting calendar?

**Comment by samumantha** [comment]
Good point, I switched it back and forth multiple times now. 
Landed on the 2 different documents to keep the community call one clean and not to mix it up.
But did not consider the two calendar events... 
But then I would maybe rather have the team confused than the new people 🤔

Not sure what is best solution though. 

Would you have it all in one?

**Comment by bast** [comment]
Two documents is fine but what I meant is that there should not be two cal invites at the same time pointing to two documents. So we could exclude community call dates from the team meeting calendar. Then it's still a meeting every week but every fourth week it will point to a different document. And hopefully people don't use some bookmarks or shortcuts but follow the calendar.

Possible confusion is only on the team side, not on the new visitor side.

**Comment by samumantha** [comment]
Ah, now I understand. Very good point indeed. 

Is it easy to do to adjust the team call calendar entry to skip every 4th time?

Another option would be to keep the team meeting document rather empty and always move the notes to archive, then I think it would be ok to share the doc with team meeting and community call.

**Comment by samumantha** [comment]
Updated to use same document as team meeting

**Pull request merged**
